name: 'rust docker action test'
description: 'hello world'
inputs:
  repo:  
    description: 'repo'
    required: true
  repo_token:
    description: 'repo-token'
    required: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.repo-token }}
